### ISSUE TITLE
Sandbox URL is harcoded for PBShippingAuthentication::refreshToken

### ISSUE THREAD

**Issue by ildar-aim** [PitneyBowes/pitneybowes-shipping-api-php#1]
https://github.com/PitneyBowes/pitneybowes-shipping-api-php/blob/6c00fe0613eedfce84cfd07b54fb569d71c5a724/lib/pbshipping/authentication.php#L54

**Comment by be002ts** [comment]
Thanks for pointing it out. The code has been corrected and will set to sandbox and production according to configuration
